site_name: Shortcuts
site_url: https://ReySi.github.io
site_author: Simon Rey
site_description: A collection of my most important shortcuts

remote_branch: gh-pages

nav:
  - About: index.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
